# Generated by Django 6.0.3 on 2026-03-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('polera', 'Poleras'), ('poleron', 'Polerones'), ('accesorio', 'Accesorios')], default='General', max_length=20),
            preserve_default=False,
        ),
    ]
