# Generated by Django 6.0.3 on 2026-03-27 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_producto_descripcion_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrito',
            unique_together={('usuario', 'producto')},
        ),
    ]
