# Generated by Django 6.0.3 on 2026-04-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_billetera_usuario_remove_compra_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='edad',
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
